#!/usr/bin/ruby

def usage
  puts "Usage: #{$0} <file>"
  exit 1
end

def hoppity(n)
  (1 .. n).each do |i|
    s = i % 15 == 0 ? 'Hop' \
      : i %  5 == 0 ? 'Hophop' \
      : i %  3 == 0 ? 'Hoppity' \
      : nil
    puts s unless s.nil?
  end
end

usage if ARGV.length != 1

n = File.read(ARGV[0]).to_i
hoppity(n)
